version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_server
    ports:
      - "9000:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: application
      MONGO_INITDB_ROOT_PASSWORD: tf123
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    driver: bridge
